# Generated by Django 5.2.6 on 2025-09-25 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(choices=[('VEHICULO', 'Vehículo'), ('PERSONA', 'Persona'), ('MIXTO', 'Mixto')], default='MIXTO', max_length=50)),
            ],
            options={
                'db_table': 'puntos_acceso',
            },
        ),
        migrations.CreateModel(
            name='IntentoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('DENEGADO', 'Denegado')], max_length=10)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('accion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentos_acceso', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentos_acceso', to='app.vehiculo')),
            ],
            options={
                'db_table': 'intentos_acceso',
            },
        ),
        migrations.CreateModel(
            name='EntradaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='app.intentoacceso')),
            ],
            options={
                'db_table': 'entradas_salidas',
            },
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('punto_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camaras', to='app.puntoacceso')),
            ],
            options={
                'db_table': 'camaras',
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PLACA', 'Placa'), ('ROSTRO', 'Rostro')], max_length=10)),
                ('captura', models.ImageField(blank=True, null=True, upload_to='reconocimientos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='app.camara')),
            ],
            options={
                'db_table': 'reconocimientos',
            },
        ),
        migrations.AddField(
            model_name='intentoacceso',
            name='reconocimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intento', to='app.reconocimiento'),
        ),
    ]
