# Generated by Django 5.2.6 on 2025-09-16 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_servicio_cargo_pago_cargoservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ci', models.CharField(blank=True, max_length=30, null=True)),
                ('celular', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'visitantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('pase_conocido', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='app.apartamento')),
            ],
            options={
                'db_table': 'vehiculos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_inicio', models.TimeField(default=django.utils.timezone.now)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='app.apartamento')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_cerradas', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_registradas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='app.vehiculo')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='app.visitante')),
            ],
            options={
                'db_table': 'visitas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['placa'], name='vehiculos_placa_0848cc_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['apartamento', 'placa'], name='vehiculos_apartam_3959a3_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['fecha', 'apartamento'], name='visitas_fecha_7f5e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['visitante', 'apartamento'], name='visitas_visitan_5ca15e_idx'),
        ),
    ]
