# Generated by Django 5.2.6 on 2025-09-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_areacomun_reserva_detallereserva_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areacomun',
            old_name='aforo',
            new_name='capacidad',
        ),
    ]
