# Generated by Django 5.2.6 on 2025-09-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_aforo_areacomun_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('APROBADA', 'APROBADA'), ('CANCELADA', 'CANCELADA'), ('COMPLETADA', 'COMPLETADA')], default='PENDIENTE', max_length=12),
        ),
    ]
