# Generated by Django 5.2.6 on 2025-09-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('APROBADA', 'APROBADA'), ('CANCELADA', 'CANCELADA'), ('COMPLETADA', 'COMPLETADA')], default='PENDIENTE', max_length=12),
        ),
    ]
